---
- name: install build depends
  yum: name={{ item }} state=present
  with_items:
  - "{{ rbenv_yum_packages }}"
  become: true

- name: install extra build depends
  yum: name={{ item }} state=present
  with_items: '{{ rbenv_extra_depends }}'
  become: true
